-- CREA BASE DE DATOS
CREATE DATABASE `TFM_QCH` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- TABLA USUARIOS
CREATE TABLE `USUARIOS` (
  `ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `APELLIDO1` varchar(100) NOT NULL,
  `APELLIDO2` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `TOKEN_PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- TABLA ROLES
CREATE TABLE `ROLES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- INSERTA ROLES
INSERT INTO ROLES (ID, NOMBRE) VALUES(1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NOMBRE) VALUES(2, 'ROLE_USER');

-- TABLA USUARIO_ROL
CREATE TABLE `USUARIO_ROL` (
  `USUARIO` varchar(100) NOT NULL,
  `ROL` int NOT NULL,
  PRIMARY KEY (`USUARIO`,`ROL`),
  KEY `USUARIO_ROL_FK_1` (`ROL`),
  CONSTRAINT `USUARIO_ROL_FK` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `USUARIO_ROL_FK_1` FOREIGN KEY (`ROL`) REFERENCES `ROLES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- TABLA GRUPOS_INGREDIENTES
CREATE TABLE GRUPO_INGREDIENTE (
	ID INT auto_increment NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	RACIONES_SEMANA INT NOT NULL,
	CONSTRAINT GRUPO_INGREDIENTE_pk PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- INSERTA GRUPOS DE INGREDIENTES
INSERT INTO GRUPO_INGREDIENTE (NOMBRE, RACIONES_SEMANA) VALUES 
('Esenciales', 7),
('Carne', 3),
('Carne grasa', 2),
('Cereales', 7),
('Especias', 7),
('Fruta', 7),
('Frutos secos', 7),
('Hortalizas', 7),
('Leches y derivados', 3),
('Legumbres', 7),
('Pasta', 4),
('Pescado', 4),
('Verduras', 7);

-- TABLA INGREDIENTES
CREATE TABLE INGREDIENTES (
	ID INT auto_increment NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	GRUPO INT NOT NULL,
	CONSTRAINT INGREDIENTES_pk PRIMARY KEY (ID),
	CONSTRAINT INGREDIENTES_FK FOREIGN KEY (GRUPO) REFERENCES grupo_ingrediente(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- TABLA TIPO RECETA
CREATE TABLE TIPO_RECETA (
	ID INT auto_increment NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	CONSTRAINT tipo_receta_pk PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- INSERTAR TIPOS RECETA
INSERT INTO TIPO_RECETA (NOMBRE) VALUES ('Bebida'),('Aperitivo'),('Plato'),('Postre');

-- TABLA RECETAS
CREATE TABLE RECETAS (
	ID INT auto_increment NOT NULL,
	TITULO varchar(100) NOT NULL,
	DESCRIPCION varchar(1000) NOT NULL,
	INSTRUCCIONES varchar(4000) NOT NULL,
	FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	USUARIO VARCHAR(100),
	TIPO INT NOT NULL,
	PUBLICADA BOOL DEFAULT FALSE NOT NULL,
	CONSTRAINT RECETAS_pk PRIMARY KEY (ID),
	CONSTRAINT RECETAS_FK FOREIGN KEY (USUARIO) REFERENCES usuarios(ID),
	CONSTRAINT RECETAS_FK_1 FOREIGN KEY (TIPO) REFERENCES tipo_receta(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- TABLA LIKES RECETAS
CREATE TABLE LIKE_RECETA (
	USUARIO varchar(100) NOT NULL,
	RECETA INT NOT NULL,
	CONSTRAINT LIKE_RECETA_pk PRIMARY KEY (USUARIO,RECETA),
	CONSTRAINT LIKE_RECETA_FK FOREIGN KEY (USUARIO) REFERENCES usuarios(ID),
	CONSTRAINT LIKE_RECETA_FK_1 FOREIGN KEY (RECETA) REFERENCES recetas(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

-- TABLA INGREDIENTES RECETAS
CREATE TABLE ingrediente_receta (
	INGREDIENTE INT NOT NULL,
	RECETA INT NOT NULL,
	CANTIDAD varchar(100) NOT NULL,
	CONSTRAINT ingrediente_receta_pk PRIMARY KEY (INGREDIENTE,RECETA),
	CONSTRAINT ingrediente_receta_FK FOREIGN KEY (INGREDIENTE) REFERENCES ingredientes(ID),
	CONSTRAINT ingrediente_receta_FK_1 FOREIGN KEY (RECETA) REFERENCES recetas(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;