-- CREA BASE DE DATOS
CREATE DATABASE `TFM_QCH` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

-- TABLA USUARIOS
CREATE TABLE `USUARIOS` (
  `ID` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `NOMBRE` varchar(100) NOT NULL,
  `APELLIDO1` varchar(100) NOT NULL,
  `APELLIDO2` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `TOKEN_PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- TABLA ROLES
CREATE TABLE `ROLES` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- TABLA USUARIO_ROL
CREATE TABLE `USUARIO_ROL` (
  `USUARIO` varchar(100) NOT NULL,
  `ROL` int NOT NULL,
  PRIMARY KEY (`USUARIO`,`ROL`),
  KEY `USUARIO_ROL_FK_1` (`ROL`),
  CONSTRAINT `USUARIO_ROL_FK` FOREIGN KEY (`USUARIO`) REFERENCES `USUARIOS` (`ID`),
  CONSTRAINT `USUARIO_ROL_FK_1` FOREIGN KEY (`ROL`) REFERENCES `ROLES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- INSERTA ROLES
INSERT INTO ROLES (ID, NOMBRE) VALUES(1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, NOMBRE) VALUES(2, 'ROLE_USER');